name: iOS Simulator Build (Appetize) v36
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4'

      - name: Install tools
        run: brew install xcodegen

      - name: Ensure asset catalog root exists
        run: |
          mkdir -p Assets.xcassets
          if [ ! -f Assets.xcassets/Contents.json ]; then echo '{}' > Assets.xcassets/Contents.json; fi

      - name: Update deployment target
        run: sed -i '' 's/15.0/16.0/g' project.yml

      - name: Remove existing Xcode project
        run: rm -rf S2Pass.xcodeproj

      - name: Generate Xcode project
        run: xcodegen

      - name: Downgrade Xcode project format
        run: |
          PBXPROJ="S2Pass.xcodeproj/project.pbxproj"
          # Set objectVersion to 56 for compatibility with Xcode 15.x
          sed -i '' 's/objectVersion = [0-9]\{1,3\};/objectVersion = 56;/' "$PBXPROJ"

      - name: Build
        run: |
          xcodebuild -scheme S2Pass -sdk iphonesimulator -configuration Release \
            -destination "generic/platform=iOS Simulator" \
            -derivedDataPath "$PWD/build" \
            BUILD_LIBRARY_FOR_DISTRIBUTION=NO \
            ONLY_ACTIVE_ARCH=NO \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY= \
            DEVELOPMENT_TEAM='' \
            build

      - name: Package .app for Appetize
        run: |
          APP_DIR="$PWD/build/Build/Products/Release-iphonesimulator"
          APP_PATH=$(find "$APP_DIR" -maxdepth 1 -name "*.app" -type d | head -n 1)
          ditto -c -k --sequesterRsrc --keepParent "$APP_PATH" "$GITHUB_WORKSPACE/AppetizeBuild.app.zip"
          ls -lh "$GITHUB_WORKSPACE/AppetizeBuild.app.zip"

      - name: Upload artifact (Appetize)
        uses: actions/upload-artifact@v4
        with:
          name: appetize-simulator-app
          path: ${{ github.workspace }}/AppetizeBuild.app.zip
          if-no-files-found: error

      - name: Complete job
        run: echo "Done"
