name: iOS Simulator Build (Appetize) v32
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    env:
      CONFIG: Release
      SDK: iphonesimulator
      DEST: generic/platform=iOS Simulator
      DERIVED: build
    steps:
      - uses: actions/checkout@v4

      - name: Set up Xcode 16.x
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16'

      - name: Install tools
        run: |
          brew update
          brew install xcodegen

      - name: Ensure asset catalog root exists
        run: |
          mkdir -p Sources/S2Pass/Assets.xcassets
          if [ ! -f Sources/S2Pass/Assets.xcassets/Contents.json ]; then
            echo '{ "info": { "version": 1, "author": "xcode" } }' > Sources/S2Pass/Assets.xcassets/Contents.json
          fi

      - name: Update deployment target
        run: |
          sed -i.bak 's/IPHONEOS_DEPLOYMENT_TARGET: 15.0/IPHONEOS_DEPLOYMENT_TARGET: 16.0/' project.yml

      - name: Generate Xcode project
        run: |
          xcodegen generate

      - name: Build
        run: |
          set -eo pipefail
          xcodebuild \
            build \
            -scheme S2Pass \
            -sdk "$SDK" \
            -configuration "$CONFIG" \
            -destination "$DEST" \
            -derivedDataPath "$DERIVED" \
            ARCHS=arm64 \
            BUILD_LIBRARY_FOR_DISTRIBUTION=NO \
            ONLY_ACTIVE_ARCH=NO \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM="" \
            ASSETCATALOG_COMPILER_APPICON_NAME="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY=""

      - name: Package .app for Appetize
        run: |
          set -euo pipefail
          APP_DIR="$DERIVED/Build/Products/Release-iphonesimulator"
          APP_NAME=$(ls "$APP_DIR" | grep '.app$' | head -n 1)
          cd "$APP_DIR"
          echo "Zipping $APP_NAME with ditto"
          ditto -c -k --sequesterRsrc --keepParent "$APP_NAME" "AppetizeBuild.app.zip"
          mv "AppetizeBuild.app.zip" "$GITHUB_WORKSPACE/AppetizeBuild.app.zip"

      - name: Upload artifact (Appetize)
        uses: actions/upload-artifact@v4
        with:
          name: appetize-simulator-app
          path: AppetizeBuild.app.zip

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: xcodebuild-log
          path: ${{ github.workspace }}/xcodebuild.log
          if-no-files-found: warn
