name: iOS Simulator Build (Appetize) v16
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    env:
      CONFIG: Release
      SDK: iphonesimulator
      DEST: generic/platform=iOS Simulator
      DERIVED: build

    steps:
      - uses: actions/checkout@v4

      - name: Set up Xcode 16.x
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16'

      - name: Show tool versions
        run: |
          set -e
          xcodebuild -version
          xcode-select -p
          sw_vers
          echo "Workspace:" "$GITHUB_WORKSPACE"
          ls -la

      - name: Bootstrap project.yml and Info.plist if missing
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p Sources/S2Pass
          if [ ! -f project.yml ]; then
            cat > project.yml <<'EOF'
name: S2Pass

configs:
  Debug: debug
  Release: release

settings:
  IPHONEOS_DEPLOYMENT_TARGET: 15.0
  TARGETED_DEVICE_FAMILY: "1,2"

targets:
  S2Pass:
    type: application
    platform: iOS
    sources:
      - path: Sources/S2Pass
    resources:
      - path: Sources/S2Pass/Assets.xcassets
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.hudsonoss.S2Pass
      SWIFT_VERSION: 5.0
    scheme: {}
    info:
      path: Sources/S2Pass/Info.plist
      properties:
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleName: S2Pass
        CFBundleDisplayName: S2Pass
        CFBundleShortVersionString: 1.0
        CFBundleVersion: 1
        UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
EOF
          fi
          if [ ! -f Sources/S2Pass/Info.plist ]; then
            cat > Sources/S2Pass/Info.plist <<'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleIdentifier</key>
    <string>com.hudsonoss.S2Pass</string>
    <key>CFBundleName</key>
    <string>S2Pass</string>
    <key>CFBundleDisplayName</key>
    <string>S2Pass</string>
    <key>CFBundleShortVersionString</key>
    <string>1.0</string>
    <key>CFBundleVersion</key>
    <string>1</string>
    <key>UILaunchScreen</key>
    <dict/>
    <key>UIApplicationSceneManifest</key>
    <dict>
        <key>UIApplicationSupportsMultipleScenes</key>
        <false/>
    </dict>
    <key>LSRequiresIPhoneOS</key>
    <true/>
</dict>
</plist>
EOF
          fi
          echo "Top-level files:"; ls -la
          echo "Sources/S2Pass:"; ls -la Sources/S2Pass || true

      - name: Install XcodeGen
        run: |
          brew update
          brew install xcodegen

      - name: Generate Xcode project
        run: |
          set -euo pipefail
          xcodegen generate
          xcodebuild -list -project S2Pass.xcodeproj

      - id: detect
        name: Detect project/workspace and scheme
        run: |
          set -euo pipefail
          XCPROJ=$(ls -1 **/*.xcodeproj 2>/dev/null | head -n1 || true)
          XCWORK=$(ls -1 **/*.xcworkspace 2>/dev/null | head -n1 || true)
          if [ -n "$XCWORK" ]; then
            FILE="$XCWORK"; KIND=workspace
            LIST=$(xcodebuild -list -workspace "$FILE" 2>/dev/null || true)
          elif [ -n "$XCPROJ" ]; then
            FILE="$XCPROJ"; KIND=project
            LIST=$(xcodebuild -list -project "$FILE" 2>/dev/null || true)
          else
            echo "No .xcodeproj/.xcworkspace after generation" >&2
            exit 1
          fi
          echo "$LIST"
          SCHEME=$(echo "$LIST" | awk '/Schemes:/{flag=1;next}/^$/{flag=0}flag' | head -n1 | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
          if [ -z "${SCHEME:-}" ]; then
            echo "No shared scheme detected" >&2
            exit 1
          fi
          echo "file=$FILE" >> "$GITHUB_OUTPUT"
          echo "kind=$KIND" >> "$GITHUB_OUTPUT"
          echo "scheme=$SCHEME" >> "$GITHUB_OUTPUT"

      - name: Build (signing OFF)
        run: |
          set -euo pipefail
          DERIVED_ABS="$GITHUB_WORKSPACE/$DERIVED"
          if [ "${{ steps.detect.outputs.kind }}" = "workspace" ]; then
            xcodebuild \
              -workspace "${{ steps.detect.outputs.file }}" \
              -scheme "${{ steps.detect.outputs.scheme }}" \
              -sdk "$SDK" -configuration "$CONFIG" \
              -destination "$DEST" -derivedDataPath "$DERIVED_ABS" \
              CODE_SIGNING_ALLOWED=NO \
              build | tee "$GITHUB_WORKSPACE/xcodebuild.log"
          else
            xcodebuild \
              -project "${{ steps.detect.outputs.file }}" \
              -scheme "${{ steps.detect.outputs.scheme }}" \
              -sdk "$SDK" -configuration "$CONFIG" \
              -destination "$DEST" -derivedDataPath "$DERIVED_ABS" \
              CODE_SIGNING_ALLOWED=NO \
              build | tee "$GITHUB_WORKSPACE/xcodebuild.log"
          fi

      - name: Package .app for Appetize
        run: |
          set -euo pipefail
          DERIVED_ABS="$GITHUB_WORKSPACE/$DERIVED"
          PROD_DIR=$(find "$DERIVED_ABS/Build/Products" -type d -maxdepth 1 -name "*-iphonesimulator" | head -n1 || true)
          if [ -z "$PROD_DIR" ]; then
            echo "No simulator products found in $DERIVED_ABS/Build/Products" >&2
            exit 1
          fi
          APP_PATH=$(ls -d "$PROD_DIR"/*.app 2>/dev/null | head -n1 || true)
          if [ -z "$APP_PATH" ]; then
            echo "No .app found in $PROD_DIR" >&2
            exit 1
          fi
          (cd "$PROD_DIR" && zip -r AppetizeBuild.app.zip "$(basename "$APP_PATH")")
          mv "$PROD_DIR/AppetizeBuild.app.zip" "$GITHUB_WORKSPACE/AppetizeBuild.app.zip"

      - name: Upload artifact (Appetize)
        uses: actions/upload-artifact@v4
        with:
          name: appetize-simulator-app
          path: AppetizeBuild.app.zip

      - name: Upload logs (if present)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: xcodebuild-log
          path: ${{ github.workspace }}/xcodebuild.log
          if-no-files-found: ignore
