name: iOS Simulator Build (Appetize) v39
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true
    env:
      ASSETCATALOG_COMPILER_APPICON_NAME: ""
    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.4'
      - name: Install xcodegen
        run: brew install xcodegen
      - name: Ensure asset catalog
        run: mkdir -p Assets.xcassets/AppIcon.appiconset
      - name: Update deployment target
        run: sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 18.0;/IPHONEOS_DEPLOYMENT_TARGET = 16.0;/g' project.yml || true
      - name: Remove existing Xcode project
        run: rm -rf S2Pass.xcodeproj
      - name: Generate Xcode project
        run: xcodegen generate
      - name: Build for iOS Simulator
        run: xcodebuild -scheme S2Pass -sdk iphonesimulator -configuration Release -derivedDataPath build -destination 'generic/platform=iOS Simulator' BUILD_LIBRARY_FOR_DISTRIBUTION=NO ONLY_ACTIVE_ARCH=NO CODE_SIGN_STYLE=Manual CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO CODE_SIGN_IDENTITY="" DEVELOPMENT_TEAM=""
      - name: Package .app for Appetize
        run: |
          APP_DIR="$PWD/build/Build/Products/Release-iphonesimulator"
          APP_NAME=$(find "$APP_DIR" -maxdepth 1 -name '*.app' -type d | head -n 1)
          cd "$APP_DIR"
          zip -r "$GITHUB_WORKSPACE/AppetizeBuild.app.zip" "$(basename "$APP_NAME")"
      - uses: actions/upload-artifact@v4
        with:
          name: appetize-simulator-app
          path: AppetizeBuild.app.zip
      - if: always()
        uses: actions/upload-artifact@v4
        with:
          name: xcodebuild-log
          path: build/Build/*/Logs
