name: iOS Simulator Build (Appetize) v21

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    env:
      CONFIG: Release
      SDK: iphonesimulator
      DEST: generic/platform=iOS Simulator
      DERIVED: build

    steps:
      - uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16'

      - name: Install tools
        run: |
          brew update
          brew install xcodegen

      - name: Update deployment target
        run: |
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET: 15.0/IPHONEOS_DEPLOYMENT_TARGET: 16.0/' project.yml

      - name: Ensure asset catalog root exists
        run: |
          mkdir -p Sources/S2Pass/Assets.xcassets
          if [ ! -f Sources/S2Pass/Assets.xcassets/Contents.json ]; then
            echo '{ "info": { "version": 1, "author": "xcode" } }' > Sources/S2Pass/Assets.xcassets/Contents.json
          fi

      - name: Generate Xcode project
        run: |
          xcodegen generate
          xcodebuild -list -project S2Pass.xcodeproj

      - name: Build (signing off, bypass AppIcon requirement)
        run: |
          set -euo pipefail
          xcodebuild \
            -project S2Pass.xcodeproj \
            -scheme S2Pass \
            -sdk "$SDK" \
            -configuration "$CONFIG" \
            -destination "$DEST" \
            -derivedDataPath "$DERIVED" \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM="" \
            ASSETCATALOG_COMPILER_APPICON_NAME=""

      - name: Package .app for Appetize
        run: |
          set -euo pipefail
          DERIVED_ABS="$GITHUB_WORKSPACE/$DERIVED"
          PROD_DIR=$(find "$DERIVED_ABS/Build/Products" -type d -maxdepth 2 -name "*-iphonesimulator" | head -n1 || true)
          if [ -z "$PROD_DIR" ]; then
            DEFAULT_DERIVED=$(ls -td ~/Library/Developer/Xcode/DerivedData/S2Pass-* 2>/dev/null | head -n1 || true)
            if [ -n "$DEFAULT_DERIVED" ]; then
              PROD_DIR=$(find "$DEFAULT_DERIVED/Build/Products" -type d -maxdepth 2 -name "*-iphonesimulator" | head -n1 || true)
            fi
          fi
          if [ -z "$PROD_DIR" ]; then
            echo "No simulator products found" >&2
            exit 1
          fi
          APP_PATH=$(ls -d "$PROD_DIR"/*.app 2>/dev/null | head -n1 || true)
          if [ -z "$APP_PATH" ]; then
            echo "No .app found in $PROD_DIR" >&2
            exit 1
          fi
          ZIP_NAME="AppetizeBuild.app.zip"
          (cd "$PROD_DIR" && zip -r "$ZIP_NAME" "$(basename "$APP_PATH")")
          mv "$PROD_DIR/$ZIP_NAME" "$GITHUB_WORKSPACE/$ZIP_NAME"

      - name: Upload artifact (Appetize)
        uses: actions/upload-artifact@v4
        with:
          name: appetize-simulator-app
          path: AppetizeBuild.app.zip

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: xcodebuild-log
          path: $GITHUB_WORKSPACE/xcodebuild.log
          if-no-files-found: warn
