name: iOS Simulator Build (Appetize) v27

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    env:
      CONFIG: Release
      SDK: iphonesimulator
      DEST: generic/platform=iOS Simulator
      DERIVED: build

    steps:
      - uses: actions/checkout@v4

      - name: Set up Xcode 16.x
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16'

      - name: Install tools
        run: |
          brew update
          brew install xcodegen

      - name: Ensure asset catalog root exists
        run: |
          mkdir -p Sources/S2Pass/Assets.xcassets
          if [ ! -f Sources/S2Pass/Assets.xcassets/Contents.json ]; then
            echo '{ "info": { "version": 1, "author": "xcode" } }' > Sources/S2Pass/Assets.xcassets/Contents.json
          fi

      - name: Generate Xcode project
        run: |
          xcodegen generate
          xcodebuild -list -project S2Pass.xcodeproj

      - name: Build (signing off, x86_64)
        run: |
          set -euo pipefail
          xcodebuild \
            -project S2Pass.xcodeproj \
            -scheme S2Pass \
            -sdk "$SDK" \
            -configuration "$CONFIG" \
            -destination "$DEST" \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGNING_REQUIRED=NO \
            DEVELOPMENT_TEAM="" \
            ARCHS=x86_64 \
            EXCLUDED_ARCHS=arm64 \
            IPHONEOS_DEPLOYMENT_TARGET=16.0 \
            -derivedDataPath "$DERIVED" \
            ASSETCATALOG_COMPILER_APPICON_NAME="" \
            | tee "$GITHUB_WORKSPACE/xcodebuild.log"

      - name: Package .app for Appetize
        run: |
          set -euo pipefail
          # Find the first .app bundle in the derived data directory
          APP_PATH=$(find "$DERIVED" -type d -name "*.app" -print -quit)
          if [ -z "$APP_PATH" ]; then
            echo "No .app bundle found in $DERIVED"
            find "$DERIVED" -maxdepth 4 -type d -name "*.app" || true
            exit 1
          fi
          APP_DIR=$(dirname "$APP_PATH")
          APP_NAME=$(basename "$APP_PATH")
          (cd "$APP_DIR" && zip -r AppetizeBuild.app.zip "$APP_NAME")
          mv "$APP_DIR/AppetizeBuild.app.zip" "$GITHUB_WORKSPACE/AppetizeBuild.app.zip"

      - name: Upload artifact (Appetize)
        uses: actions/upload-artifact@v4
        with:
          name: appetize-simulator-app
          path: AppetizeBuild.app.zip

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: xcodebuild-log
          path: ${{ github.workspace }}/xcodebuild.log
          if-no-files-found: warn
