name: Simulator Preview
on:
  workflow_dispatch:
jobs:
  preview:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4'
      - name: Boot simulator & record
        run: |
          xcrun simctl boot "iPhone 15"
          xcrun simctl io booted recordVideo preview.mp4 & REC=$!
          xcrun simctl launch booted com.hudsonoss.S2Pass || true
          sleep 20
          kill $REC || true
      - uses: actions/upload-artifact@v4
        with:
          name: simulator-preview
          path: preview.mp4
